<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Robin Donatello" />


<title>Lesson 07 - Creating graphics</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 45px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 50px;
  margin-top: -50px;
}

.section h2 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h3 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h4 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h5 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h6 {
  padding-top: 50px;
  margin-top: -50px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">MATH 130</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="http://www.norcalbiostat.com/data/">
    <span class="fa fa-database"></span>
     
    Data
  </a>
</li>
<li>
  <a href="https://www.datacamp.com/">
    <span class="fa fa-code"></span>
     
    Data Camp
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="faq.html">
    <span class="fa fa-question"></span>
     
    Help/FAQ
  </a>
</li>
<li>
  <a href="syllabus.html">
    <span class="fa fa-info-circle"></span>
     
    Syllabus
  </a>
</li>
<li>
  <a href="http://www.norcalbiostat.com/">
    <span class="fa fa-paw"></span>
     
    Dr. D's Website
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Lesson 07 - Creating graphics</h1>
<h4 class="author"><em>Robin Donatello</em></h4>
<h4 class="date"><em>Last Updated 08-18-2018</em></h4>

</div>


<blockquote>
<p>This lesson is a brief excerpt from Robin Donatello’s <a href="full_data_viz_tutorial.html">[Full data viz tutorial]</a>.</p>
</blockquote>
<hr />
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Visualizing your data is hands down the most important thing you can learn to do. Seeing is critical to understanding. There are two audiences in mind when creating data visualizations:</p>
<ol style="list-style-type: decimal">
<li>For your eyes only (FYEO). These are quick and dirty plots, without annotation. Meant to be looked at once or twice.</li>
<li>To share with others. These need to completely stand on their own. Axes labels, titles, colors as needed, possibly captions.</li>
</ol>
<p>You will see, and slowly learn, how to add these annotations and how to clean up your graphics to make them sharable. Functions inside the <code>ggplot2</code> package automatically does a lot of this work for you. Remember this package has to be loaded prior to being able to access the functions within.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)</code></pre></div>
<p>Use the navbar to the left to help you navigate this long document.</p>
<div id="the-syntax-of-ggplot" class="section level2">
<h2>The syntax of <code>ggplot</code></h2>
<p>The reason we use the functions in <code>ggplot2</code> is for consistency in the structure of it’s arguments. Here is a bare bones generic plotting function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(data, <span class="kw">aes</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y, <span class="dt">col=</span>col, <span class="dt">fill=</span>fill, <span class="dt">group=</span>group)) <span class="op">+</span><span class="st">  </span><span class="kw">geom_THING</span>() </code></pre></div>
<div id="required-arguments" class="section level3">
<h3>Required arguments</h3>
<ul>
<li><code>data</code>: What data set is this plot using? This is ALWAYS the first argument.</li>
<li><code>aes()</code>: This is the <em>aestetics</em> of the plot. What’s varible is on the x, what is on the y? Do you want to color by another variable, perhaps fill some box by the value of another variable, or group by a variable.</li>
<li><code>geom_THING()</code>: Every plot has to have a geometry. What is the shape of the thing you want to plot? Do you want to plot points - use <code>geom_points()</code>. Want to connect those points with a line? Use <code>geom_lines()</code>. We will see many varieties in this lab.</li>
</ul>
</div>
</div>
<div id="the-diamonds-data" class="section level2">
<h2>The Diamonds Data</h2>
<p>We will use a subset of the <code>diamonds</code> dataset that comes with the <code>ggplot2</code> package. This dataset contains the prices and other attributes of almost 54,000 diamonds. Review <code>?diamonds</code> to learn about the variables we will be using.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">data</span>(<span class="st">&quot;diamonds&quot;</span>)
<span class="kw">set.seed</span>(<span class="dv">1410</span>) <span class="co"># Make the sample reproducible</span>
dsmall &lt;-<span class="st"> </span>diamonds[<span class="kw">sample</span>(<span class="kw">nrow</span>(diamonds), <span class="dv">1000</span>), ]</code></pre></div>
<hr />
</div>
</div>
<div id="univariate-one-variable" class="section level1">
<h1>Univariate (One Variable)</h1>
<div id="categorical-variables" class="section level2">
<h2>Categorical variables</h2>
<p>Both Nominal and Ordinal data types can be visualized using the same methods: tables, barcharts and pie charts.</p>
<div id="tables" class="section level3">
<h3>Tables</h3>
<p>Tables are the most common way to get summary statistics of a categorical variable. The <code>table()</code> function produces a frequency table, where each entry represents the number of records in the data set holding the corresponding labeled value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(dsmall<span class="op">$</span>cut)</code></pre></div>
<pre><code>## 
##      Fair      Good Very Good   Premium     Ideal 
##        27        83       226       277       387</code></pre>
<p>There are 27 Fair quality diamonds, 83 good quality and 387 Ideal quality diamonds in this sample.</p>
</div>
<div id="barcharts-barplots" class="section level3">
<h3>Barcharts / Barplots</h3>
<p>A Barchart or barplot takes these frequencies, and draws bars along the X-axis where the height of the bars is determined by the frequencies seen in the table.</p>
<p>The geometry needed to draw a barchart in ggplot is <code>geom_bar()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>cut)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
</div>
<div id="continuous-variable" class="section level2">
<h2>Continuous variable</h2>
<p>The price, carat, and depth of the diamonds are all continuous variables.</p>
<div id="histograms" class="section level3">
<h3>Histograms</h3>
<p>Rather than showing the value of each observation, we prefer to think of the value as belonging to a <em>bin</em>. The height of the bars in a histogram display the frequency of values that fall into those of those bins.</p>
<p>Since the x-axis is continuous the bars touch. This is unlike the barchart that has a categorical x-axis, and vertical bars that are separated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>depth)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="density-plots" class="section level3">
<h3>Density plots</h3>
<p>To get a better idea of the true shape of the distribution we can “smooth” out the bins and create what’s called a <code>density</code> plot or curve. Notice that the shape of this distribution curve is much more… “wigglier” than the histogram may have implied.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>depth)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>()</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="histograms-density" class="section level3">
<h3>Histograms + density</h3>
<p>Often is is more helpful to have the density (or kernal density) plot <em>on top of</em> a histogram plot.</p>
<ul>
<li>The syntax starts the same, we’ll add a new geom, <code>geom_density</code> and color the line blue.</li>
<li>Then we add the histogram geom using <code>geom_histogram</code> but must specify that the y axis should be on the density, not frequency, scale.
<ul>
<li>Note that this has to go inside the aestetic statement <code>aes()</code>.</li>
</ul></li>
<li>I’m also going to get rid of the fill by using <code>NA</code> so the colored bars don’t plot over the density line.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>depth)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density..), <span class="dt">colour=</span><span class="st">&quot;black&quot;</span>, <span class="dt">fill=</span><span class="ot">NA</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="boxplots" class="section level3">
<h3>Boxplots</h3>
<p>Another very common way to visualize the distribution of a continuous variable is using a boxplot. Boxplots are useful for quickly identifying where the bulk of your data lie. R specifically draws a “modified” boxplot where values that are considered outliers are plotted as dots.</p>
<div id="base" class="section level4">
<h4>base</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(dsmall<span class="op">$</span>depth)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Notice that the only axis labeled is the y=axis. Like a dotplot the x axis, or “width”, of the boxplot is meaningless here. We can make the axis more readable by flipping the plot on it’s side.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(dsmall<span class="op">$</span>depth, <span class="dt">horizontal =</span> <span class="ot">TRUE</span>, <span class="dt">main=</span><span class="st">&quot;Distribution of diamond prices&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Dollars&quot;</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Horizontal is a bit easier to read in my opinion.</p>
<p>What about ggplot? ggplot doesn’t really like to do univariate boxplots. You’ll see those later when we create one boxplot per group.</p>
<hr />
</div>
</div>
</div>
</div>
<div id="bivariate-two-variables" class="section level1">
<h1>Bivariate (Two Variables)</h1>
<div id="categorical-v.-categorical" class="section level2">
<h2>Categorical v. Categorical</h2>
<div id="two-way-tables" class="section level3">
<h3>Two-way Tables</h3>
<p>Cross-tabs, cross-tabulations and two-way tables (all the same thing, different names) can be created by using the <code>table()</code> function.</p>
<div id="frequency-table" class="section level4">
<h4>Frequency table</h4>
<p>The frequency table is constructed using the <code>table()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(dsmall<span class="op">$</span>cut, dsmall<span class="op">$</span>color)</code></pre></div>
<pre><code>##            
##              D  E  F  G  H  I  J
##   Fair       4  5  4  3 10  1  0
##   Good      13  6 19 16 10 13  6
##   Very Good 30 60 37 50 26 18  5
##   Premium   39 42 40 55 46 40 15
##   Ideal     63 69 52 77 65 40 21</code></pre>
<p>There are 4 Fair diamonds with color D, and 21 Ideal quality diamonds with color J.</p>
</div>
<div id="cell-proportions" class="section level4">
<h4>Cell proportions</h4>
<p>Wrapping <code>prop.table()</code> around a table gives you the <strong>cell</strong> proportions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.table</span>(<span class="kw">table</span>(dsmall<span class="op">$</span>cut, dsmall<span class="op">$</span>color))</code></pre></div>
<pre><code>##            
##                 D     E     F     G     H     I     J
##   Fair      0.004 0.005 0.004 0.003 0.010 0.001 0.000
##   Good      0.013 0.006 0.019 0.016 0.010 0.013 0.006
##   Very Good 0.030 0.060 0.037 0.050 0.026 0.018 0.005
##   Premium   0.039 0.042 0.040 0.055 0.046 0.040 0.015
##   Ideal     0.063 0.069 0.052 0.077 0.065 0.040 0.021</code></pre>
<p>0.4% of all diamonds are D color and Fair cut, 2.1% are J color and Ideal cut.</p>
</div>
<div id="row-proportions" class="section level4">
<h4>Row proportions</h4>
<p>To get the <strong>row</strong> proportions, you specify <code>margin=1</code>. The percentages now add up to 1 across the rows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(dsmall<span class="op">$</span>cut, dsmall<span class="op">$</span>color), <span class="dt">margin=</span><span class="dv">1</span>),<span class="dv">3</span>)</code></pre></div>
<pre><code>##            
##                 D     E     F     G     H     I     J
##   Fair      0.148 0.185 0.148 0.111 0.370 0.037 0.000
##   Good      0.157 0.072 0.229 0.193 0.120 0.157 0.072
##   Very Good 0.133 0.265 0.164 0.221 0.115 0.080 0.022
##   Premium   0.141 0.152 0.144 0.199 0.166 0.144 0.054
##   Ideal     0.163 0.178 0.134 0.199 0.168 0.103 0.054</code></pre>
<p>14.8% of all Fair quality diamonds are color D. 5.4% of all Ideal quality diamonds have color J.</p>
</div>
<div id="column-proportions" class="section level4">
<h4>Column proportions</h4>
<p>To get the <strong>column</strong> proportions, you specify <code>margin=2</code>. The percentages now add up to 1 down the columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(dsmall<span class="op">$</span>cut, dsmall<span class="op">$</span>color), <span class="dt">margin=</span><span class="dv">2</span>),<span class="dv">3</span>)</code></pre></div>
<pre><code>##            
##                 D     E     F     G     H     I     J
##   Fair      0.027 0.027 0.026 0.015 0.064 0.009 0.000
##   Good      0.087 0.033 0.125 0.080 0.064 0.116 0.128
##   Very Good 0.201 0.330 0.243 0.249 0.166 0.161 0.106
##   Premium   0.262 0.231 0.263 0.274 0.293 0.357 0.319
##   Ideal     0.423 0.379 0.342 0.383 0.414 0.357 0.447</code></pre>
<p>2.7% of all D color diamonds are of Fair quality. 44.7% of all J color diamonds are of Ideal quality.</p>
</div>
</div>
<div id="grouped-bar-charts" class="section level3">
<h3>Grouped bar charts</h3>
<p>To compare proprtions of one categorical variable within the same level of another, is to use grouped barcharts.</p>
<p>Plot the cut on the x axis, but then <code>fill</code> using the second categorical variable. This has the effect of visualizing the <strong>row</strong> percents from the table above. The percent of color, within each type of cut.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>cut, <span class="dt">fill=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The default is a stacked barchart. So add the argument <code>position=dodge</code> inside the <code>geom_bar</code> layer to put the bars side by side.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>cut, <span class="dt">fill=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>And look, an automatic legend. What if I wanted to better compare cut within color group? This is the <strong>column</strong> percentages. Just switch which variable is the x axis and which one is used to fill the colors!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>color, <span class="dt">fill=</span>cut)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>And this easy change is why we love <code>ggplot2</code>.</p>
</div>
</div>
<div id="continuous-v.-continuous" class="section level2">
<h2>Continuous v. Continuous</h2>
<div id="scatterplot" class="section level3">
<h3>Scatterplot</h3>
<p>The most common method of visualizing the relationship between two continuous variables is by using a scatterplot.</p>
<p>With ggplot we specify both the x and y variables, and add a point.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">y=</span>price)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<div id="adding-lines-to-the-scatterplots" class="section level3">
<h3>Adding lines to the scatterplots</h3>
<p>Two most common trend lines added to a scatterplots are the “best fit” straight line and the “lowess” smoother line. This is done by adding a <code>geom_smooth()</code> layer.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">y=</span>price)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>() </code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Here the point-wise confidence interval for this lowess line is shown in grey. If you want to turn the confidence interval off, use <code>se=FALSE</code>. Also notice that the smoothing geom uses a different function or window than the <code>lowess</code> function used in base graphics.</p>
<p>Here it is again using the <code>ggplot</code> plotting function and adding another <code>geom_smooth()</code> layer for the <code>lm</code> (linear model) line in blue, and the lowess line (by not specifying a method) in red.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">y=</span>price)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">se=</span><span class="ot">FALSE</span>, <span class="dt">method=</span><span class="st">&quot;lm&quot;</span>, <span class="dt">color=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">se=</span><span class="ot">FALSE</span>, <span class="dt">color=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
</div>
<div id="continuous-v.-categorical" class="section level2">
<h2>Continuous v. Categorical</h2>
<p>Create an appropriate plot for a continuous variable, and plot it for each level of the categorical variable.</p>
<div id="grouped-boxplots" class="section level3">
<h3>Grouped boxplots</h3>
<p>A simple addition, just define your x and y accordingly. Specifying your <code>fill</code> to be the same variable as your <code>x</code>, gives you an automatic legend.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>color, <span class="dt">y=</span>carat, <span class="dt">fill=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="adding-violins-to-the-boxplot" class="section level3">
<h3>Adding violins to the boxplot</h3>
<p>A violin plot is like a density plot, turned on it’s side, and reflected around the axis for symmetry purposes. Overlaying a boxplot and a violin plot serves a similar purpose to Histograms + Density plots. It shows outliers, the location of most the data, and better shows the shape/skew of the distribution</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>color, <span class="dt">y=</span>carat, <span class="dt">fill=</span>color)) <span class="op">+</span>
<span class="st">        </span><span class="kw">geom_violin</span>(<span class="dt">alpha=</span>.<span class="dv">1</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">        </span><span class="kw">geom_boxplot</span>(<span class="dt">alpha=</span>.<span class="dv">5</span>, <span class="dt">width=</span>.<span class="dv">2</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="grouped-histograms" class="section level3">
<h3>Grouped histograms</h3>
<p>By default ggplot wants to overlay all plots on the same grid. This doesn’t look to good with histograms or density plots. The top layer hides the others.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">fill=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()
b &lt;-<span class="st"> </span><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">fill=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>() 
gridExtra<span class="op">::</span><span class="kw">grid.arrange</span>(a,b, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-24-1.png" width="960" /></p>
<p>The solid fills are still difficult to read, so we can either turn down the alpha (turn up the transparency) or only color the lines and not the fill.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d &lt;-<span class="st"> </span><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">fill=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="dt">alpha=</span>.<span class="dv">2</span>)
e &lt;-<span class="st"> </span><span class="kw">ggplot</span>(dsmall, <span class="kw">aes</span>(<span class="dt">x=</span>carat, <span class="dt">col=</span>color)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>() 
gridExtra<span class="op">::</span><span class="kw">grid.arrange</span>(d,e, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="07_graphs_files/figure-html/unnamed-chunk-25-1.png" width="960" /></p>
<p>These last few plots demonstrate how to place two plots side by side.</p>
<ol style="list-style-type: decimal">
<li>Each plot is stored as an object (<code>a</code>, <code>b</code>, <code>d</code>, <code>e</code>)</li>
<li>The <code>grid.arrange</code> function is located within the <code>gridExtra</code> package, plots the specified objects in the number of columns specified by <code>ncol</code>.</li>
</ol>
<hr />
</div>
</div>
</div>
<div id="additional-resources" class="section level1">
<h1>Additional Resources</h1>
<p>For a <strong>full</strong> , and comprehensive reference guide on how to do nearly anything in ggplot – this is by far my favorite reference <a href="http://www.cookbook-r.com/Graphs/" class="uri">http://www.cookbook-r.com/Graphs/</a> I reference things in there (like how to remove or change the title of a legend) constantly.</p>
<ul>
<li>R Graphics: <a href="https://www.stat.auckland.ac.nz/~paul/RGraphics/rgraphics.html" class="uri">https://www.stat.auckland.ac.nz/~paul/RGraphics/rgraphics.html</a> The best book about using base graphics</li>
<li>STHDA: Statisical tools for high-throughput data analysis. <a href="http://www.sthda.com/english/" class="uri">http://www.sthda.com/english/</a></li>
<li>Quick-R: <a href="http://www.statmethods.net/graphs/index.html">Basic Graphs</a></li>
<li>Quick-R: <a href="http://www.statmethods.net/advgraphs/ggplot2.html">ggplot2</a></li>
<li>Books
<ul>
<li>ggplot2 <a href="http://ggplot2.org/book/" class="uri">http://ggplot2.org/book/</a> or <a href="http://amzn.com/0387981403" class="uri">http://amzn.com/0387981403</a></li>
<li>qplot <a href="http://ggplot2.org/book/qplot.pdf" class="uri">http://ggplot2.org/book/qplot.pdf</a></li>
</ul></li>
<li>Help lists
<ul>
<li>ggplot2 mailing list <a href="http://groups.google.com/group/ggplot2" class="uri">http://groups.google.com/group/ggplot2</a></li>
<li>stackoverflow <a href="http://stackoverflow.com/tags/ggplot2" class="uri">http://stackoverflow.com/tags/ggplot2</a></li>
<li>Chico R users group</li>
</ul></li>
</ul>
<p>For any other Google Search be sure to limit searches to within the past year or so. R packages get updated very frequently, and many functions change or become obsolete.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
