---
title: "Frequently Asked Questions"
date: "Last Updated `r Sys.time()`"
output: html_document
---

# Where can I get help using R outside of class time? 

### Online
* Chico [R User Group](https://groups.google.com/forum/#!forum/chico-rug) Google email list and discussion board. 
    - Contribute your own solutions and advice as you can. 
* Stack Overflow using the `R` tag https://stackoverflow.com/questions/tagged/r 
    - Both of these are most helpful when you prepare a [minimal working example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of your problem for the other users. 
* UCLA IDRE https://stats.idre.ucla.edu/r/ 
* Cookbook for R http://www.cookbook-r.com/
* R Examples repository http://dwoll.de/rexrepos/index.html 


### In Person: 

* [**Math Learning Lab**](http://www.csuchico.edu/math/Tutoring.shtml)
    - MLIB 4th floor
    - Mariby Cruz, Mitch Borgert, Ricardo Aguilar, Jerry Tucay 

* **Community Coding Sessions** - TBD for Fall 18

> _Come code with us! Bring your Data Science and coding questions, data, and projects. We aim to provide a helpful and friendly working environment where you can work, ask questions or discuss ideas related to R, Python, Data Science, or more generally data visualization and analysis._

* **Robin Donatello** - Stat professor. Holt 202. rdonatello@csuchico.edu 
    - OH TBD
    - Most community coding sessions. 
* **Edward Roualdes** - Stat professor. Holt 204. eroualdes@csuchico.edu
    - OH TBD
    - Most community coding sessions. 
* **Eduardo Gomez** - peer mentor. egomez42@mail.csuchico.edu
* **Ricardo Aguilar** - peer mentor. raguilar11@mail.csuchico.edu
* **Mariby Cruz** - peer mentor.  mcruz27@mail.csuchico.edu
    - available for personal tutoring, including weekends


# What other computers on campus have R? 

* The three reserve computers in the first floor library. You have to ask to use these. 
* Butte 207 & 211 are open computer labs.

    
    
# Common Error Messages
Taken from: http://blog.revolutionanalytics.com/2015/03/the-most-common-r-error-messages.html

* `could not find function` errors, usually caused by typos or not loading a required package
* `Error in if` errors, caused by non-logical data or missing values passed to R's `if` conditional statement
* `Error in eval` errors, caused by references to objects that don't exist
* `cannot open` errors, caused by attempts to read a file that doesn't exist or can't be accessed
* `no applicable method` errors, caused by using an object-oriented function on a data type it doesn't support
* `subscript out of bounds` errors, caused by trying to access an element or dimension that doesn't exist
* package errors caused by being unable to install, compile or load a package.
    
    