
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(kableExtra)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r echo=FALSE}
rawdat <- read_excel("schedule_130.xlsx")
cdat   <- rawdat %>% mutate(Date = format(date, "%m/%d"), 
                            Topics = topic, Preparation = prep, Evaluation = eval) %>% 
              select(Week, Date, Topics, Preparation, Evaluation, topic, prep, eval)

# parse topics
topiclist <- which(!is.na(cdat$topic))
cdat$Topics[topiclist] <- paste0("<ul><li>", cdat$topic[topiclist], "</li></ul>")
cdat$Topics[topiclist] <- gsub("(+.)\\*", "</li><li>", cdat$Topics[topiclist])

# parse prep
preplist <- which(!is.na(cdat$prep))
cdat$Preparation[preplist] <- paste0("<ul><li>", cdat$prep[preplist], "</li></ul>")
cdat$Preparation[preplist] <- gsub("(+.)\\*", "</li><li>", cdat$Preparation[preplist])

# parse evaluations
evallist <- which(!is.na(cdat$eval))
cdat$Evaluation[evallist] <- paste0("<ul><li>", cdat$eval[evallist], "</li></ul>")
cdat$Evaluation[evallist] <- gsub("(+.)\\*", "</li><li>", cdat$Evaluation[evallist])
```

```{r results='asis', echo=FALSE}
out <- select(cdat, Week, Date, Topics, Preparation, Evaluation)

knitr::kable(out, align="l", escape=FALSE) %>% 
  kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered")) %>% 
  column_spec(1, width="1%") %>% column_spec(2, width="1%") %>%
  column_spec(3, width="20%") %>% column_spec(4, width="30%") %>%
  column_spec(5, width="30%")
```



