---
output:
  pdf_document: default
  html_document: default
---

# Math 130: Introduction to R - Spring 18 

[[Download this syllabus as a PDF]](syllabus.pdf)

# Course Description
This course is designed as a primer to get the complete novice up and running with the basic knowledge of how to use the statistical programming language R in an environment that emphasizes reproducible research and literate programming for data analysis. The target audience is anyone who wants to do their own data analysis. The course will cumulate with an peer-evaluated exploratory data analysis on either a pre-specified data set or your data set of choice. 


# Logistics

* **Course Website:** https://norcalbiostat.github.io/MATH130/ 
* **Prerequisites:** Basic computer literacy  
* **Workshop style:** This workshop style class runs for the first 5 weeks of the semester only (1/22-2/22). There will be one lab assigned per week. What is not finished in class is considered homework. 

|                        |        Section 01       |       Section 02       |
|:-----------------------|:-----------------------:|:----------------------:|
| **Meeting Days/Times** | TR 11-12:15             | MW 3-4:45              |
| **Meeting Location**   | Butte 207               | Holt 155               |
| **Instructor**         | Robin Donatello         | Edward Roualdes        |
| **Office Location**    | Holt 202                | Holt 204               |
| **Office Phone**       | 898-5767                | 898-5807               |
| **E-mail**             | rdonatello@csuchico.edu | eroualdes@csuchico.edu |


## Required Materials

* A reliable laptop that you can install programs onto. Contact me for alternatives.
    - Mac / Windows are easy. Linux/Unix installs are more difficult, but not impossible. 
* Reliable internet connection while on and off campus.
* A Data Camp account. This is an online tool to learn R. A link will be emailed to you that will allow you to create an account to join the online classroom class. Be sure to use your real name for credit.  
* Join the [Chico R Users Google Group](https://groups.google.com/forum/#!forum/chico-rug) - This is our discussion forum to ask (and answer) questions outside of class. 
    - There is also a [Meetup group](https://www.meetup.com/Chico-R-Users-Group/) - optional but useful if you want to stay connected to the community and learn about upcoming events. 
* Free programming software. Instructions and links to download, install and setup these programs can be found at https://norcalbiostat.netlify.com/post/software-overview/ 
    - [R](https://cran.r-project.org/)
    - [R Studio](https://www.rstudio.com/)
    - [LaTeX](https://www.latex-project.org/): optional but very nice for producing professional quality PDF reports. 
        - Windows: Get the proTex distribution
        - Mac: You only have one choice. 

## Grading
Credit / No Credit. There are 100 points available in this course. You must earn 70 points to receive credit for the course. 

* Attendance: 2 pts per day (20 pts)
* Assignments:
    - Data Camp (10 pts)
    - Lab 1 (10 pts)
    - Lab 2 (10 pts)
    - Lab 3 (10 pts)
    - Lab 4 (10 pts)
* Project
    - Project (20 pts)
    - Peer Review (10 pts)

## Assignments
 
* All assignment and data files are posted on the course website. 
* Assignment file due dates and submission instructions are up to the individual instructor. 

## Learning Outcomes
By the end of the course, students will be able to

* Import external data into R.
* Calculate summary statistics.
* Create new variables using different data types. 
* Create informative data visualizations and tables.
* Perform data management techniques such as subsetting, grouping, summarizing. 
* Create a reproducible research document.
* Conduct an exploratory data analysis in a reproducible manner.


## Schedule of Topics
The general outline of topics is listed below. A detailed most up to date schedule can be found on the course website. 

* Intro to the R language and it's packages
* R Studio suite of awesomeness
* Reproducible Research with R Markdown
* Functions
* Getting data into R
* Managing the spreadsheet-like data frame
* Data Visualization
* Data Manipulation and Aggregation
* Exploratory Data Analysis


## Adding and Dropping the course
This course only runs for a few weeks and all materials are available on the course website. It will be difficult to get caught up if you add the class after the first week. The last day to add or drop classes without special permission by the instructor is 2/2/18. No adds or dropps are allowed after 2/16/18 without a serious and compelling reason approved by the instructor, department chair, and college dean.


## Americans with Disabilities Act
If you need course adaptations or accommodations because of a disability or chronic illness,  or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations.

Accessibility Resource Center  
530-898-5959   
Student Services Center 170  
arcdept@csuchico.edu  






