---
title: 'Exploratory Data Analysis Project'
output: 
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

Time to put everything you learned in this class into action. In an exploratory data analysis (EDA) you are just looking at (exploring) the data and learning about the data and possible relationships between variables. This is not a formal statistical analysis, you cannot make any claims about groups being statistically different. This is just descriptive. You are allowed and encouraged to hypothesize why you observe certain relationships or data characteristics, just be sure not to draw any conclusions from the data. 
 
# Instructions
Using your data set of choice, describe the relationship between two variables. 
This should include

1. A description of the data
2. A _Univariate_ description of each of the variables under consideration. 
3. A _Bivariate_ comparison between the two variables of interest. 
4. A short summary of implications.  

All descriptions (univariate and bivariate) must be done using graphics, summary statistics, and words. 


This is a very vague set of instructions for a reason. I want you to explore and choose a pair of variables that you find interesting. Create tables, graphics, grouped summary statistics (mean of the continuous variable across levels of the categorical variable). Whatever you need to do to understand the relationship between these two measures. 

Use the grading rubric at the end of this document for guidance as to what you should present, in what order, and level of detail you need to present.

## Data

You have a choice here. If you are currently working on some data that you would like to explore, talk with me to get your data set approved. 

If you do not have your own data, you can choose from one of the following data sets, all of which can be downloaded from the [Data](../../data/Datasets.html) page of the course website. Here are some viable choices: 


* **NCbirths**: Information on births recorded in North Carolina in 2004 and health behaviors of their mothers. 
* **Depression**: Level of depression (`cesd`), health care, and demographic characteristics. 
* **Arm Strength**: Strength of the bones within the dominant, and non-dominant arm for baseball players and normal people. 
* **High School and Beyond**: Educational, vocational, and personal development of elementary and high school students. 
* **Police Shootings**: Characteristics of individuals killed by police in 2015. 
* **Email Spam**: Characteristics of emails used to predict if the email is spam or not. 
* **HIV**: Data on adolescent children living with HIV positive parents. 

Any other data sets require instructor approval. 

## Submission

* To allow for adequate time for peer grading the submission deadline is a strict cutoff. Really late assignments won't be accepted. 
* Knit your file to HTML, then upload to [here](https://www.dropbox.com/request/S3KxRFTY7ZcHhZSRHaYT) by the due date. 

> You must name your file "EDA_name" for proper processing. 


## Peer Review 

After the submission deadline, your analysis projects will be randomly assigned to two of your classmates for peer grading. This means you will score and provide feedback on 2 of your classmates reports. I will also score all projects.

* All submissions will be posted to a [peer review](https://norcalbiostat.github.io/peer_review/math130_eda.html) website.
* Go here and click on your assigned reviewee's name 
* Record your scores in a [Google Form](https://goo.gl/forms/7I4zsYpSsiZpgKyH3).

This data will be downloaded, cleaned and processed (all using R of course) by the instructor to generate your project grade. 


## Guidelines

* Knit early and often. As often as every time you include a new R code chunk. 
* Spell check your report prior to submission using RStudio. 
* Re-read your report and edit for clarification and removing duplicated information. 
* Remove superfluous code and output (i.e. printing a data set to the screen). 
* This is to be independent work. Papers that are too similar will receive no credit. 
* Look at the grading rubric to help you decide the level of detail required. 


# Grading 
Your final project grade will be a weighted between the average of 30%
peer reviews ($\bar{PR}$) and 70% instructor review ($IR$): $(.3*\bar{PR} + .7*IR)$. 
Your submission is worth 30 points, the peer review is 5 pts. 


## Scoring Rubric
The criteria below is what you will be graded on. Below each criteria is an example of the points awarded for the level of competency. 


1. **Reproducibility**: Was the report created in R, using Markdown, in a
   reproducible manner? 
    - (Novice) The report appears to have been written in another program and R
          output and/or figures look to have been copied/pasted into the document. 
    - (Competent)  The analysis report was written in RMarkdown, but vital pieces of
          information such as the code to create the plots or to read in the data are missing. 
    - (Proficient) This analysis is fully reproducible. It is clear where the data came
           from, and how it is used at each step. This code could be downloaded
           and run on another machine with only a change to the data location. 

2. **Data Description**: Provide a description of the data set and the variables of interest. 
    - (Novice) There is no description or the description is a copy of the help file.
    - (Competent) There is a minor description of the data but not enough to understand
             what is being measured or compared. 
    - (Proficient) The data description is clear and concise, it is clear to me what data
             is being analyzed and where it was obtained. 

3. **Univariate Description**: Fully describe the distribution of _each variable_ by itself 
    - (Novice) There are no numerical or graphical summaries provided. 
    - (Competent) Only numeric or only graphical summaries were created, but no textual
             description. 
    - (Proficient) The variable was fully described using both numeric and graphical summary
             methods. This information was summarized below the output in a paragraph
             form. 
4. **Bivariate Comparison**: Describe the relationship between the two chosen variables. 
    - (Novice) No comparison was made, or the variables were compared, but
             inappropriate graphics or summary statistics were created. 
    - (Competent) The variables were compared using appropriate graphical methods and
             grouped summary statistics were created, but nothing was discussed. 
    - (Proficient) The variables were compared using appropriate graphical methods and
             a paragraph textual explanation of what the summaries showed. 

5. **Implications**: Briefly summarize or describe how these findings can inform policy, 
              further research, or the general public. 
    - (Novice) There is no summary. 
    - (Competent) The summary makes statements or claims that are not supported by 
             evidence in the report. 
    - (Proficient) The conclusion is clear and concise, the statements are supported
             by evidence shown in this report. 

6. **Organization / Grammer**: 
    - (Novice) Only R code, output is present. There is no discussion of results. 
             Tons of extra R code that is not relevant to the discussion is present. 
    - (Competent)  An attempt was made to discuss the results, but the explanations are 
             not in a report format or there are some large grammar and/or spelling
             problems. Some R code that is not relevant to the analysis question at
             hand is being displayed. 
    - (Proficient) The report was spell written in well edited, full English sentences, and
             spell checked prior to submission. The report flowed well and followed 
             the required order of discussion topics: overall information about the
             data, univariate descriptions, then bivariate descriptions. 
 



