---
title: "Lesson 02 - Introduction to R Markdown and Homework 1"
author: "Robin Donatello"
date: "Last Updated `r format(Sys.Date(), '%m-%d-%Y')`"
output:
  pdf_document:
    toc: no
  html_document:
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: yes
---


# Introduction

* In this lesson you will learn to write a document using R markdown, integrate live R code into a literate statistical program, compile R markdown documents using `knitr` and related tools, and organize a data analysis sandbox so that it is reproducible and accessible to others.


### Student Learning Objectives

* After completing this lesson students will be able to create a reproducible R Markdown document that integrates written text, R code and output into a literate document.  

# Code Appearance

* R code in these notes will look like this, code in a colored box and the output directly following with two proceeding pound signs (#). 
```{r}
2+2
```

* Any R code, variables, functions or data sets referenced in text will look `like this`. 

* Links to download files or to external websites will be [[bracketed]](www.norcalbiostat.com). 

# Preparation
* R and R Studio must be installed
* The following R packages must be installed: `rmarkdown` and `knitr`

```r
install.packages("rmarkdown")
install.packages("knitr")
```

* A class folder created on your computer using one of the options below:
    - ALL CAPS (MATH130)
    - no caps (math130)
    - snake_case (math_130)
    - CamelCase (Math130) is not recommended (do you want to remember what letters were capitalized?)

# Setting preferences

It is advised to set the following preferences to retain your sanity when debugging. 

* In RStudio the file menu go to Tools then Global Options.
* Uncheck "Restore .RData into workspace at startup" 
* Where it says "Save workspace to .RData on exit:" Select "Never""
* Click apply then ok to close that window.
  
This will ensure that when you restart R you do not "carry forward" objects such as data sets that you were working on in a prior assignment. 

It is _highly_ recommended to completely shut down R studio when you are done working. 
    
# Test your setup

Let's create your first markdown file!

1. In R Studio go to _File_ --> _New File_ --> _R Markdown_
2. Title this document **My First R Markdown Document**, then click OK.
3. Click the small blue disk icon to save this file into your class folder. 
4. Save this file using the file name **test_markdown_document**. 
    - File names cannot have spaces or special characters.
    - Do not specify the file type. It will be set automatically. 
5. Click the **KNIT** button (has the yarn ball next to it) to convert this file into HTML. 
6. Look at the HTML file that was created. You should be able to match the code with the resulting output. 

This is what we mean by reproducible. If you make a change in the code document, and re-knit (aka compile), your changes will be reflected in the generated document. 

# Start the first homework

1. **Right click** and select **save as** (or save target as) to download [[HW 1.Rmd]](../hw/HW1.Rmd) code file to your class folder. 
2. Navigate to your class folder and double click to open this file in R Studio
    - You might have to tell your computer what program to use. 
    - <span style="color:red">Do NOT open this file from your browser window. </span>
4. Knit this file to HTML. 
5. Look at each piece of the output around problem 0. Mentally match each piece of output with the corresponding section in the RMD file. 
6. This provides a homework template for you to use to write your assignment. Write your answers directly into this document. 
    - If this doesn't look familiar, go finish the Data Camp homework first!
7. Submit the **RMD** file before the due date. I will knit the file on my machine and grade the result. Make sure it looks good before turning it in!

